# Generated by Django 4.0.3 on 2022-04-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_wallet_application', '0002_operation_description_alter_localconfiguration_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='accountingMoment',
            new_name='accounting_moment',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='executionMoment',
            new_name='execution_moment',
        ),
    ]
